### ISSUE TITLE
ITCSS refactor

### ISSUE THREAD

**Issue by furzeface** [cartridge/cartridge#37]
`elements` should be `base`, according to ITCSS guidelines.

I have created a branch which adds in directories for the other levels of ITCSS too.

**Comment by furzeface** [comment]
**Note**: if this gets approved and merged in, it will need updating in [cartridge-sass](https://github.com/cartridge/cartridge-sass) as well.

**Comment by bmds** [comment]
@furzeface Do you mind creating a linked issue on `cartridge-sass` please?

**Comment by tawashley** [comment]
Turns out I've been 'wrongly' using elements all this time then.
