### ISSUE TITLE
Remove the build or public reference in project json

### ISSUE THREAD

**Issue by andrewbrandwood** [cartridge/cartridge#55]
This is an issue in static-html also.  When running gulp the HTML page goes in a build folder but all the client assets go in a public folder.  It's not easy to just pick the complete build as they are in 2 different folders.  It's a bit confusing.

**Comment by tawashley** [comment]
With the merge of https://github.com/cartridge/cartridge/pull/51 and the cartridge release of v.2.0.0, this issue is now resolved.

Seperate work will be required on cartridge-static-html
